name: GDExtension CMake

on: [push, pull_request]

jobs:
  # build-windows:
  #   runs-on: windows-latest
  #   steps:
  #     - uses: actions/setup-python@v2
  #       with:
  #         python-version: "3.x"
  #         architecture: "x64"
  #     - uses: ilammy/msvc-dev-cmd@v1
  #     - name: build-windows-latest
  #       run: pip3 install --user scons

  build-linux:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v3
      
      - name: Install dependencies
        run: pip3 install --user scons
      
      - name: Configure (Linux)
        run: >    
          cmake -B ${{ github.workspace }}/.out 
          -DCMAKE_CXX_COMPILER=g++
          -DCMAKE_C_COMPILER=gcc 
          -DCMAKE_BUILD_TYPE=Debug 
          -S ${{ github.workspace }}
      
      - name: Build (Linux)
        run: cmake --build ${{ github.workspace }}/.out --config Debug
        
